---
- hosts: localhost
  connection: local
  become: true
  vars:
    package_names:
      Debian:
        - htop
        - git
        - tmux
        - vim-nox
        - wget
        - gpg
        - steam
        - flatpak
        - filezilla
      Archlinux:
        - htop
        - git
        - tmux
        - vim
        - wget
        - gnupg
        - steam
        - flatpak
        - filezilla
  roles:
    - role: gantsign.visual-studio-code
      when: ansible_facts['os_family'] != 'Archlinux'

  tasks:
    - name: install initial packages
      package:
        name: "{{ package_names[ansible_facts['os_family']] | default(package_names['Debian']) }}"
        state: present

    - name: Add the flatpak remote to the system installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpak packages
      community.general.flatpak:
        name:
          - com.discordapp.Discord
          - com.jetbrains.IntelliJ-IDEA-Ultimate
          - com.google.Chrome
          - com.spotify.Client
          - org.videolan.VLC
          - com.visualstudio.code

    - name: Install Snap packages
      community.general.snap:
        name:
          - docker
      when: ansible_facts['os_family'] != 'Archlinux'

    - name: Install Docker package on Arch-based systems
      package:
        name:
          - docker
        state: present
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: add ansible user
      user:
        name: ansible
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: files/sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: ensure ansible user has a cron directory
      file:
        path: /var/spool/cron
        state: directory
        owner: ansible
        group: ansible
        mode: 0755

    - name: add ansible-pull cron job
      copy:
        dest: /var/spool/cron/ansible
        owner: ansible
        group: ansible
        mode: 0600
        content: |
          */10 * * * * ansible-pull -o -U https://github.com/austin-calkins/ansible-desktop-setup.git
